Repository vaadin/hilla, pull requests merged in 2022-05, with the labels that each got.

#407 build: Node async defaultResolve comatibility in esbuild test loader
  scripts/node/esbuild.js
Labels: hilla, target/1.0

#406 fix: boolean model converts "true" and "false" to their boolean equivalents
  packages/ts/form/src/Models.ts
  packages/ts/form/test/Model.test.ts
Labels: target/1.0

#408 chore(release): build fix and npm version 1.0.9
  lerna.json
  package-lock.json
  packages/ts/form/package.json
  packages/ts/form/src/index.ts
  packages/ts/generator-typescript-cli/package.json
  packages/ts/generator-typescript-core/package.json
  packages/ts/generator-typescript-plugin-backbone/package.json
  packages/ts/generator-typescript-plugin-barrel/package.json
  packages/ts/generator-typescript-plugin-client/package.json
  packages/ts/generator-typescript-plugin-model/package.json
  packages/ts/generator-typescript-utils/package.json
  packages/ts/hilla-frontend/package.json
  packages/ts/hilla-frontend/src/index.ts
  scripts/node/esbuild.js
Labels: hilla

#411 build: set default release workflow branch name in 1.1
  .github/workflows/ts-release.yml
Labels: hilla

#410 chore: bump Maven project version to 1.2-SNAPSHOT
  packages/java/maven-plugin/pom.xml
  packages/java/parser-jvm-core/pom.xml
  packages/java/parser-jvm-plugin-backbone/pom.xml
  packages/java/parser-jvm-plugin-model/pom.xml
  packages/java/parser-jvm-plugin-nonnull/pom.xml
  packages/java/parser-jvm-plugin-transfertypes/pom.xml
  packages/java/parser-jvm-test-utils/pom.xml
  packages/java/parser-jvm-utils/pom.xml
  packages/java/runtime-plugin-transfertypes/pom.xml
  pom.xml
Labels: hilla

#409 fix: boolean model converts "true" and "false" to their boolean equivalents (#406) (CP: 1.0)
  packages/ts/form/src/Models.ts
  packages/ts/form/test/Model.test.ts
Labels: hilla

#421 feat(form): support vaadin-combo-box string value / use model in field strategy
  packages/ts/form/src/Binder.ts
  packages/ts/form/src/Field.ts
  packages/ts/form/test/Field.test.ts
Labels: hilla, target/1.0, target/1.1

#424 fix!: Use /HILLA/push instead of /VAADIN/... for the push endpoint
  packages/ts/hilla-frontend/src/FluxConnection.ts
Labels: target/1.1

#420 feat: Allow binding a subscription to a context
  packages/ts/hilla-frontend/src/Connect.ts
  packages/ts/hilla-frontend/src/FluxConnection.ts
  packages/ts/hilla-frontend/test/FluxConnection.test.ts
Labels: target/1.1
