Repository vaadin/hilla, pull requests merged in 2022-11, with the labels that each got.

#618 test: Set proper scope on test artifacts
  packages/java/tests/pom.xml
  packages/java/tests/spring/endpoints/pom.xml
Labels: target/1.2, target/1.3

#651 chore: remove the permission checking step
  .github/workflows/validation.yml
Labels: target/1.2, target/1.3

#656 fix: generate declare keyword for createEmptyValue methods
  packages/java/endpoint/src/main/resources/dev/hilla/generator/EntityModelTemplate.mustache
  packages/java/endpoint/src/test/resources/dev/hilla/generator/tsmodel/expected-TsFormEndpoint.ts
  packages/ts/form/test/TestModels.ts
  packages/ts/generator-typescript-plugin-model/src/EntityModelProcessor.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormAnnotationsModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormArrayTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormDataPrimitivesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityHierarchyModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityIdModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormNonnullTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormOptionalTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormRecordTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormTemporalTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormValidationConstraintsModel.snap.ts
Labels: hilla, target/1.2, target/1.3

#658 build: set correct default branch in cherry pick script
  scripts/cherryPick.cjs
Labels: hilla

#652 fix: support BigInteger as a long
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoSourceModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassRefSignatureModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/SpecializedModel.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/BaseSignatureModelTests.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/ClassInfoModelTests.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/ClassRefSignatureModelTests.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/SchemaProcessor.java
  packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/simpletype/SimpleTypeEndpoint.java
  packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/simpletype/openapi.json
  packages/ts/generator-typescript-plugin-backbone/test/simple-type/SimpleType.json
  packages/ts/generator-typescript-plugin-backbone/test/simple-type/fixtures/SimpleTypeEndpoint.snap.ts
Labels: target/1.2, target/1.3

#650 fix: use EndpointExposed annotation name when configuring parser in Maven Plugin
  packages/java/maven-plugin/src/main/java/dev/hilla/maven/ParserProcessor.java
Labels: target/1.2, target/1.3

#677 chore: fix wrong scope for org.apache.maven dep
  packages/java/maven-plugin/pom.xml
Labels: target/1.1, target/1.2, target/1.3

#657 build: simplify build matrix
  .github/workflows/validation.yml
Labels: hilla
