Repository vaadin/hilla, pull requests merged in 2023-11, with the labels that each got.

#1631 fix(generator-typescript-plugin-model): update ObjectModel generics
  packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts
Labels: hilla, target/2.3

#1616 fix: allow filtering float properties
  packages/java/endpoint/src/main/java/dev/hilla/crud/PropertyStringFilterSpecification.java
  packages/java/endpoint/src/test/java/dev/hilla/crud/FilterTest.java
  packages/java/endpoint/src/test/java/dev/hilla/crud/TestObject.java
Labels: target/2.3

#1659 fix(endpoint): support prefix and context path with reactive endpoints (#1543) (CP: 2.3)
  packages/java/endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
  packages/java/endpoint/src/main/java/dev/hilla/push/PushConfigurer.java
  packages/java/tests/spring/security-contextpath/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-contextpath/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security-jwt/src/main/java/com/vaadin/flow/spring/fusionsecurityjwt/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-jwt/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-urlmapping/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security/frontend/views/private/private-view.ts
  packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
  packages/ts/frontend/src/FluxConnection.ts
  packages/ts/frontend/test/FluxConnection.test.ts
Labels: hilla

#1660 fix(endpoint): support prefix and context path with reactive endpoints (#1543) (CP: main)
  packages/java/endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
  packages/java/endpoint/src/main/java/dev/hilla/push/PushConfigurer.java
  packages/java/tests/spring/security-contextpath/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-contextpath/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security-jwt/src/main/java/com/vaadin/flow/spring/fusionsecurityjwt/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-jwt/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-urlmapping/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security/frontend/views/private/private-view.ts
  packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
  packages/ts/frontend/src/FluxConnection.ts
  packages/ts/frontend/test/FluxConnection.test.ts
Labels: hilla

#1662 [Snyk] Upgrade org.apache.maven.plugin-tools:maven-plugin-annotations from 3.9.0 to 3.10.1
  packages/java/maven-plugin/pom.xml
Labels: target/2.3

#1652 [Snyk] Upgrade io.swagger.core.v3:swagger-core from 2.2.16 to 2.2.17
  pom.xml
Labels: target/2.3

#1694 fix(form): use correct call for interpolateMessageCallback
  package-lock.json
  packages/ts/form/package.json
  packages/ts/form/src/Binder.ts
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/src/BinderRoot.ts
  packages/ts/form/src/types.d.ts
  packages/ts/form/test/Validation.test.ts
Labels: hilla, target/2.2, target/2.3

#1697 fix(form): use correct call for interpolateMessageCallback (#1694) (CP: 2.3)
  packages/ts/form/package.json
  packages/ts/form/src/Binder.ts
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/src/BinderRoot.ts
  packages/ts/form/src/util.d.ts
  packages/ts/form/test/Validation.test.ts
Labels: hilla

#1698 fix(form): use correct call for interpolateMessageCallback (#1694) (CP: 2.2)
  packages/ts/form/package.json
  packages/ts/form/src/Binder.ts
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/src/BinderRoot.ts
  packages/ts/form/src/util.d.ts
  packages/ts/form/test/Validation.test.ts
  packages/ts/react-form/src/index.ts
Labels: hilla

#1752 chore: constrain `@types/react` version
  package-lock.json
  packages/ts/react-auth/package.json
  packages/ts/react-crud/package.json
  packages/ts/react-form/package.json
Labels: target/2.3

#1745 [Snyk] Upgrade io.swagger.core.v3:swagger-core from 2.2.17 to 2.2.18
  pom.xml
Labels: target/2.3, target/2.4

#1766 chore(react-crud): add registration for AutoCrud, AutoGrid, AutoForm
  packages/ts/react-crud/src/autocrud-feature.ts
  packages/ts/react-crud/src/autoform-feature.ts
  packages/ts/react-crud/src/autogrid-feature.ts
  packages/ts/react-crud/src/index.ts
  packages/ts/react-crud/src/util.ts
  scripts/register.js
Labels: hilla, target/2.4

#1772 chore: upgrade vaadin-parent to 2.2.1
  pom.xml
Labels: target/2.4

#1776 fix(react-crud): render nested properties in auto form
  packages/ts/react-crud/src/autoform-field.tsx
  packages/ts/react-crud/test/autoform.spec.tsx
  packages/ts/react-crud/test/autogrid.spec.tsx
  packages/ts/react-crud/test/test-models-and-services.ts
Labels: target/2.4

#1765 chore: forbid unintentional exclusive tests
  .eslintrc
  .lintstagedrc.js
  .mocharc.cjs
  .mocharc.json
  karma.config.cjs
  package-lock.json
  package.json
  packages/ts/form/.lintstagedrc.js
  packages/ts/frontend/.lintstagedrc.js
  packages/ts/generator-typescript-cli/.lintstagedrc.js
  packages/ts/generator-typescript-cli/package.json
  packages/ts/generator-typescript-core/.lintstagedrc.js
  packages/ts/generator-typescript-core/package.json
  packages/ts/generator-typescript-plugin-backbone/.lintstagedrc.js
  packages/ts/generator-typescript-plugin-backbone/package.json
  packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/HierarchyRef.spec.ts
  packages/ts/generator-typescript-plugin-barrel/.lintstagedrc.js
  packages/ts/generator-typescript-plugin-barrel/package.json
  packages/ts/generator-typescript-plugin-client/.lintstagedrc.js
  packages/ts/generator-typescript-plugin-client/package.json
  packages/ts/generator-typescript-plugin-model/.lintstagedrc.js
  packages/ts/generator-typescript-plugin-model/package.json
  packages/ts/generator-typescript-plugin-push/.lintstagedrc.js
  packages/ts/generator-typescript-plugin-push/package.json
  packages/ts/generator-typescript-plugin-subtypes/.lintstagedrc.js
  packages/ts/generator-typescript-plugin-subtypes/package.json
  packages/ts/generator-typescript-utils/.lintstagedrc.js
  packages/ts/generator-typescript-utils/package.json
  packages/ts/react-auth/.lintstagedrc.js
  packages/ts/react-crud/.lintstagedrc.js
  packages/ts/react-form/.lintstagedrc.js
Labels: hilla

#1777 fix(react-crud): render nested properties in auto form (#1776) (CP: 2.4)
  packages/ts/react-crud/src/autoform-field.tsx
  packages/ts/react-crud/test/autoform.spec.tsx
  packages/ts/react-crud/test/autogrid.spec.tsx
  packages/ts/react-crud/test/test-models-and-services.ts
Labels: hilla

#1781 chore: upgrade springboot version to 3.1.6
  pom.xml
Labels: target/2.2, target/2.3

#1787 chore: make commit hook linter work
  .lintstagedrc.js
Labels: hilla

#1795 [Snyk] Upgrade io.github.classgraph:classgraph from 4.8.163 to 4.8.164
  pom.xml
Labels: target/2.3, target/2.4

#1794 [Snyk] Upgrade org.apache.maven.plugin-tools:maven-plugin-annotations from 3.10.1 to 3.10.2
  packages/java/maven-plugin/pom.xml
Labels: target/2.3, target/2.4

#1780 fix: use fixed width for row numbers column
  packages/ts/react-crud/src/autogrid.tsx
  packages/ts/react-crud/test/GridController.ts
  packages/ts/react-crud/test/autogrid.spec.tsx
Labels: target/2.4

#1809 fix: add executable names to not found message
  packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/CommandRunner.java
  packages/java/engine-core/src/test/java/dev/hilla/engine/commandrunner/CommandRunnerTest.java
Labels: target/2.3, target/2.4

#1818 chore: add rerun for IT tests
  .github/workflows/validation.yml
Labels: hilla
