Repository vaadin/hilla, pull requests merged in 2023-12, with the labels that each got.

#1737 feat(react-form): make form updatable
  package-lock.json
  packages/ts/react-form/package.json
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/test/models.ts
  packages/ts/react-form/test/useForm.spec.tsx
Labels: hilla

#1872 test: use 2.5-SNAPSHOT in Maven and Gradle tests
  packages/java/gradle-plugin/src/functionalTest/kotlin/dev/hilla/gradle/plugin/AbstractGradleTest.kt
  packages/java/tests/gradle/single-module-tests/gradle.properties
  packages/java/tests/gradle/single-module-tests/gradle/wrapper/gradle-wrapper.properties
  packages/java/tests/gradle/single-module-tests/package.json
  packages/java/tests/gradle/single-module/gradle.properties
  packages/java/tests/gradle/single-module/gradle/wrapper/gradle-wrapper.properties
  packages/java/tests/gradle/single-module/package-lock.json
  packages/java/tests/gradle/single-module/package.json
  packages/java/tests/spring/endpoints-maven-engine/pom.xml
Labels: hilla

#1879 chore: update @vaadin/common-frontend
  package-lock.json
  packages/ts/frontend/package.json
Labels: hilla

#1883 fix: properly clear time picker to an empty string
  packages/ts/form/src/Field.ts
  packages/ts/form/test/Field.test.ts
  packages/ts/form/test/TestModels.ts
Labels: target/2.4

#1914 chore: Flow 24.3.1
  pom.xml
Labels: target/2.5

#1901 fix: make init-app goal generate sources coherent with the project Hilla version
  packages/java/plugin-base/src/main/java/dev/hilla/plugin/base/HillaAppInitUtility.java
Labels: target/2.5

#1912 fix: add name property to Validator interface
  packages/ts/form/src/Validation.ts
  packages/ts/form/src/Validators.ts
  packages/ts/form/test/Validators.test.ts
Labels: target/2.4, target/2.5

#1922 chore: Bump Copilot
  pom.xml
Labels: target/2.5

#1924 fix: expose submitting state
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/test/useForm.spec.tsx
Labels: target/2.5

#1926 Update spring boot to 3.1.7
  pom.xml
Labels: target/2.4

#1887 chore: bump versions to 24.4
  .github/workflows/skip-validation.yml
  .github/workflows/validation.yml
  package-lock.json
  packages/java/endpoint/pom.xml
  packages/java/engine-core/pom.xml
  packages/java/engine-runtime/pom.xml
  packages/java/gradle-plugin/pom-portal.xml
  packages/java/gradle-plugin/pom.xml
  packages/java/gradle-plugin/src/functionalTest/kotlin/dev/hilla/gradle/plugin/AbstractGradleTest.kt
  packages/java/hilla-bom/pom.xml
  packages/java/hilla-dev-mode/pom.xml
  packages/java/hilla-dev/pom.xml
  packages/java/hilla-react-spring-boot-starter/pom.xml
  packages/java/hilla-react/pom.xml
  packages/java/hilla-spring-boot-starter/pom.xml
  packages/java/hilla/pom.xml
  packages/java/maven-plugin/pom.xml
  packages/java/parser-jvm-core/pom.xml
  packages/java/parser-jvm-plugin-backbone/pom.xml
  packages/java/parser-jvm-plugin-model/pom.xml
  packages/java/parser-jvm-plugin-nonnull/pom.xml
  packages/java/parser-jvm-plugin-subtypes/pom.xml
  packages/java/parser-jvm-plugin-transfertypes/pom.xml
  packages/java/parser-jvm-test-utils/pom.xml
  packages/java/parser-jvm-utils/pom.xml
  packages/java/plugin-base/pom.xml
  packages/java/runtime-plugin-transfertypes/pom.xml
  packages/java/tests/csrf-context/pom.xml
  packages/java/tests/csrf/pom.xml
  packages/java/tests/gradle/single-module-tests/gradle.properties
  packages/java/tests/gradle/single-module/gradle.properties
  packages/java/tests/pom.xml
  packages/java/tests/spring/endpoints discovery/pom.xml
  packages/java/tests/spring/endpoints-contextpath/pom.xml
  packages/java/tests/spring/endpoints-custom-client/pom.xml
  packages/java/tests/spring/endpoints-latest-java/pom.xml
  packages/java/tests/spring/endpoints-maven-engine/pom.xml
  packages/java/tests/spring/endpoints/pom.xml
  packages/java/tests/spring/native/pom.xml
  packages/java/tests/spring/pom.xml
  packages/java/tests/spring/react-grid-test/pom.xml
  packages/java/tests/spring/security-contextpath/pom.xml
  packages/java/tests/spring/security-jwt/pom.xml
  packages/java/tests/spring/security-urlmapping/pom.xml
  packages/java/tests/spring/security/pom.xml
  pom.xml
Labels: hilla

#1931 chore: Bump Flow and Copilot
  pom.xml
Labels: target/2.5
