Repository vaadin/hilla, pull requests merged in 2023-05, with the labels that each got.

#933 fix: Use custom connect prefix in FluxConnection
  packages/ts/hilla-frontend/src/Connect.ts
  packages/ts/hilla-frontend/src/FluxConnection.ts
  packages/ts/hilla-frontend/test/Connect.test.ts
  packages/ts/hilla-frontend/test/FluxConnection.test.ts
  packages/ts/hilla-frontend/test/mocks/atmosphere.ts
Labels: target/1.3, target/2.0

#935 fix: rebuild engine configuration at least once per run
  packages/java/engine-core/src/main/java/dev/hilla/engine/EngineConfiguration.java
  packages/java/engine-runtime/src/main/java/dev/hilla/internal/AbstractTaskEndpointGenerator.java
  packages/java/engine-runtime/src/test/java/dev/hilla/internal/TaskTest.java
Labels: target/main

#939 chore: discourage using endpoints which are not Spring Beans
  packages/java/endpoint/src/main/java/dev/hilla/EndpointController.java
Labels: target/2.0

#940 fix: hide output of test commands
  packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/CommandRunner.java
Labels: target/main

#958 fix: only add Subscription import when used
  .gitignore
  packages/ts/generator-typescript-plugin-push/src/PushProcessor.ts
  packages/ts/generator-typescript-utils/package.json
  packages/ts/generator-typescript-utils/src/memoize.ts
Labels: target/1.3, target/2.0

#975 test: Allow access to the error view
  packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/SecurityConfig.java
Labels: target/1.3, target/2.0

#914 [Snyk] Upgrade io.github.classgraph:classgraph from 4.8.154 to 4.8.157
  pom.xml
Labels: target/1.3, target/2.0

#825 [Snyk] Upgrade org.apache.maven:maven-artifact from 3.8.6 to 3.9.1
  packages/java/maven-plugin/pom.xml
Labels: target/1.3
