Repository vaadin/hilla, pull requests merged in 2023-10, with the labels that each got.

#1365 chore: replace Lerna with Nx
  .eslintrc
  .npmrc
  lerna.json
  nx.json
  package-lock.json
  package.json
  packages/ts/form/.eslintrc
  packages/ts/form/package.json
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/src/Field.ts
  packages/ts/form/test/Binder.test.ts
  packages/ts/form/test/Field.test.ts
  packages/ts/form/test/Index.test.ts
  packages/ts/form/test/Model.test.ts
  packages/ts/form/test/Validation.test.ts
  packages/ts/frontend/package.json
  packages/ts/frontend/src/index.ts
  packages/ts/frontend/test/Connect.test.ts
  packages/ts/generator-typescript-cli/package.json
  packages/ts/generator-typescript-cli/tsconfig.build.json
  packages/ts/generator-typescript-core/package.json
  packages/ts/generator-typescript-core/tsconfig.build.json
  packages/ts/generator-typescript-plugin-backbone/package.json
  packages/ts/generator-typescript-plugin-backbone/src/EndpointProcessor.ts
  packages/ts/generator-typescript-plugin-backbone/tsconfig.build.json
  packages/ts/generator-typescript-plugin-barrel/package.json
  packages/ts/generator-typescript-plugin-barrel/src/BarrelProcessor.ts
  packages/ts/generator-typescript-plugin-barrel/src/index.ts
  packages/ts/generator-typescript-plugin-barrel/tsconfig.build.json
  packages/ts/generator-typescript-plugin-client/package.json
  packages/ts/generator-typescript-plugin-client/tsconfig.build.json
  packages/ts/generator-typescript-plugin-model/package.json
  packages/ts/generator-typescript-plugin-model/src/index.ts
  packages/ts/generator-typescript-plugin-model/tsconfig.build.json
  packages/ts/generator-typescript-plugin-push/package.json
  packages/ts/generator-typescript-plugin-push/src/index.ts
  packages/ts/generator-typescript-plugin-push/tsconfig.build.json
  packages/ts/generator-typescript-plugin-subtypes/package.json
  packages/ts/generator-typescript-plugin-subtypes/src/index.ts
  packages/ts/generator-typescript-utils/.eslintrc
  packages/ts/generator-typescript-utils/package.json
  packages/ts/generator-typescript-utils/tsconfig.build.json
  packages/ts/react-auth/package.json
  packages/ts/react-auth/src/useAuth.tsx
  packages/ts/react-form/.eslintrc
  packages/ts/react-form/package.json
  packages/ts/react-form/test/useForm.spec.tsx
  packages/ts/react-grid/.eslintrc
  packages/ts/react-grid/package.json
  packages/ts/react-grid/test/autoform.spec.tsx
  packages/ts/react-grid/test/autogrid.spec.tsx
  packages/ts/react-grid/test/test-models-and-services.ts
  scripts/build.ts
  scripts/bump/package-update.js
Labels: hilla, target/2.2

#1400 fix(form): errors when defaultValue is set with array items
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/src/Validation.ts
  packages/ts/form/test/Binder.test.ts
  packages/ts/form/test/TestModels.ts
Labels: hilla, target/main

#1410 fix: disable nx cache for CI
  .github/workflows/validation.yml
  nx.json
  package.json
Labels: hilla

#1443 fix(form): errors when defaultValue is set with array items (#1400)
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/test/Binder.test.ts
  packages/ts/form/test/TestModels.ts
Labels: hilla

#1479 fix(generator-typescript-plugin-backbone): correct superclass type ref in properties
  packages/ts/generator-typescript-plugin-backbone/src/EntityProcessor.ts
  packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/HierarchyRef.json
  packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/HierarchyRef.spec.ts
  packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/fixtures/HierarchyRef.entity.snap.ts
  packages/ts/generator-typescript-plugin-backbone/test/hierarchy-ref/fixtures/HierarchyRefEndpoint.snap.ts
Labels: target/2.2

#1489 reactor(react-grid): rename filter prop to experimentalFilter
  packages/java/tests/spring/react-grid-test/frontend/views/ReadOnlyGridOrFilter.tsx
  packages/java/tests/spring/react-grid-test/frontend/views/ReadOnlyGridSinglePropertyFilter.tsx
  packages/ts/react-grid/src/autogrid.tsx
  packages/ts/react-grid/test/autogrid.spec.tsx
Labels: hilla

#1493 fix(form): iterating optional arrays immediately after initialization
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/test/Binder.test.ts
  packages/ts/form/test/TestModels.ts
Labels: target/main

#1498 fix(form): iterating optional arrays immediately after initialization (#1493)
  packages/ts/form/test/Binder.test.ts
  packages/ts/form/test/TestModels.ts
Labels: hilla

#1511 [Snyk] Upgrade io.swagger.core.v3:swagger-core from 2.2.15 to 2.2.16
  pom.xml
Labels: target/1.3, target/2.1, target/2.2

#1546 chore: update react-crud package name registration
  packages/ts/react-crud/src/index.ts
Labels: target/2.3

#1543 fix(endpoint): support prefix and context path with reactive endpoints
  packages/java/endpoint/src/main/java/dev/hilla/EndpointControllerConfiguration.java
  packages/java/endpoint/src/main/java/dev/hilla/push/PushConfigurer.java
  packages/java/tests/spring/security-contextpath/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-contextpath/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security-jwt/src/main/java/com/vaadin/flow/spring/fusionsecurityjwt/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-jwt/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security-urlmapping/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security-urlmapping/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security/frontend/views/private/private-view.ts
  packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/endpoints/BalanceEndpoint.java
  packages/java/tests/spring/security/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
  packages/ts/frontend/src/FluxConnection.ts
Labels: target/main, target/2.2, target/2.3

#1554 chore: disable nx cache for all commands in CI
  .github/workflows/validation.yml
  package.json
Labels: target/1.3, target/2.1, target/2.2, target/2.3

#1585 fix: bump react-crud dependencies
  package-lock.json
  packages/ts/react-crud/package.json
Labels: target/main

#1591 fix: Use stable Flow and TestBench
  packages/java/tests/pom.xml
  pom.xml
Labels: target/2.3

#1604 [Snyk] Upgrade org.apache.maven:maven-artifact from 3.9.4 to 3.9.5
  packages/java/maven-plugin/pom.xml
Labels: target/2.3

#1586 Add support for properties in parent classes
  packages/java/tests/spring/react-grid-test/package.json
  packages/java/tests/spring/react-grid-test/src/test/java/dev/hilla/test/reactgrid/AbstractGridTest.java
  packages/ts/react-crud/src/property-info.ts
  packages/ts/react-crud/test/test-models-and-services.ts
Labels: target/main

#1621 chore: Upgrade to Flow and components 24.2.1
  package-lock.json
  packages/java/tests/pom.xml
  pom.xml
  scripts/prepare.sh
Labels: target/2.3

#1627 chore: add CSS import system
  karma.config.cjs
  package-lock.json
  package.json
  packages/ts/form/src/BinderRoot.ts
  packages/ts/generator-typescript-plugin-push/src/PushProcessor.ts
  packages/ts/react-crud/package.json
  packages/ts/react-crud/src/autocrud.obj.css
  packages/ts/react-crud/src/autocrud.tsx
  packages/ts/react-crud/src/autogrid.obj.css
  packages/ts/react-crud/src/autogrid.tsx
  packages/ts/react-crud/src/index.ts
  packages/ts/react-crud/src/types.d.ts
  packages/ts/react-crud/test/autocrud.spec.tsx
  scripts/build.ts
Labels: hilla
