Repository vaadin/hilla, pull requests merged in 2023-03, with the labels that each got.

#794 fix(engine): use Node executable provided from Flow to run the generator
  packages/java/engine-core/pom.xml
  packages/java/engine-core/src/main/java/dev/hilla/engine/GeneratorProcessor.java
  packages/java/engine-core/src/main/java/dev/hilla/engine/GeneratorShellRunner.java
  packages/java/engine-runtime/src/main/java/dev/hilla/internal/EndpointGeneratorTaskFactoryImpl.java
  packages/java/engine-runtime/src/main/java/dev/hilla/internal/EngineRuntimeException.java
  packages/java/engine-runtime/src/main/java/dev/hilla/internal/TaskGenerateEndpointImpl.java
  packages/java/engine-runtime/src/main/java/dev/hilla/internal/runner/MavenRunner.java
  packages/java/engine-runtime/src/test/java/dev/hilla/internal/TaskGenerateEndpointTest.java
  packages/java/engine-runtime/src/test/java/dev/hilla/internal/TaskTest.java
  packages/java/maven-plugin/src/main/java/dev/hilla/maven/EngineGenerateMojo.java
  packages/java/maven-plugin/src/test/java/dev/hilla/maven/EngineGenerateMojoTest.java
Labels: hilla, target/2.0

#797 fix(engine): change how model checks for nullable fields
  packages/ts/generator-typescript-plugin-model/src/EntityModelProcessor.ts
  packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts
  packages/ts/generator-typescript-plugin-model/test/model/Model.json
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormAnnotationsModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormArrayTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormDataPrimitivesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityHierarchyModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityIdModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormOptionalTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormRecordTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormTemporalTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormValidationConstraintsModel.snap.ts
Labels: target/1.2, target/1.3, target/2.0

#798 fix(engine): let NonNullPlugin find `NonNullApi` annotation on parent packages
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoReflectionModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoSourceModel.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/PackageInfoModelTests.java
  packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java
  packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/nonnullapi/NonNullApiEndpoint.java
  packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/nonnullapi/subpackage/SubPackageDependency.java
  packages/java/parser-jvm-plugin-nonnull/src/test/resources/dev/hilla/parser/plugins/nonnull/nonnullapi/openapi.json
Labels: target/1.2, target/1.3, target/2.0

#818 fix: use classloader from current class to find packages
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoSourceModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoReflectionModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/PackageInfoSourceModel.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/Dummy.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/ClassInfoModelTests.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/PackageInfoModelTests.java
  packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java
Labels: target/1.2, target/1.3, target/2.0

#820 [Snyk] Upgrade io.github.classgraph:classgraph from 4.8.153 to 4.8.154
  pom.xml
Labels: target/2.0

#810 fix: Fix openapi parsing when there are no custom types
  packages/java/endpoint/src/main/java/dev/hilla/springnative/HillaHintsRegistrar.java
  packages/java/endpoint/src/test/java/dev/hilla/springnative/HillaHintsRegistrarTest.java
  packages/java/endpoint/src/test/resources/dev/hilla/springnative/openapi-customtype.json
  packages/java/endpoint/src/test/resources/dev/hilla/springnative/openapi-innertype.json
  packages/java/endpoint/src/test/resources/dev/hilla/springnative/openapi-nocustomtypes.json
  packages/java/endpoint/src/test/resources/dev/hilla/springnative/openapi-referring-customtypes.json
Labels: target/2.0

#834 Trim whitespace before checking length of string. Fixes #833
  packages/ts/form/src/Validators.ts
  packages/ts/form/test/Validators.test.ts
Labels: target/1.3, target/2.0

#811 fix: Make openapi.json available runtime for native apps
  packages/java/endpoint/src/main/java/dev/hilla/springnative/HillaHintsRegistrar.java
Labels: target/2.0

#835 feat(form): consider errors from HTML and Vaadin components built-in validation
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/src/Field.ts
  packages/ts/form/src/Validators.ts
  packages/ts/form/src/Validity.ts
  packages/ts/form/test/Binder.test.ts
  packages/ts/form/test/TestModels.ts
  packages/ts/form/test/Validation.test.ts
  packages/ts/form/test/Validators.test.ts
Labels: hilla, target/1.3, target/2.0

#856 fix: executing Node in Windows with spaces in path
  packages/java/engine-core/src/main/java/dev/hilla/engine/GeneratorShellRunner.java
Labels: target/2.0

#862 fix(parser): consider annotations from both fields and accessors
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/Parser.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/jackson/JacksonModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/jackson/JacksonPropertyModel.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/jackson/JacksonPropertyTypeModel.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/jackson/JacksonPropertyModelTests.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/jackson/JacksonPropertySharedTests.java
  packages/java/parser-jvm-core/src/test/java/dev/hilla/parser/models/jackson/JacksonPropertyTypeModelTests.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/EndpointExposedPlugin.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/EntityPlugin.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/TypeSignaturePlugin.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/nodes/AnnotatedNode.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/nodes/CompositeTypeSignatureNode.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/nodes/TypeSignatureNode.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/dev/hilla/parser/plugins/backbone/nodes/TypedNode.java
  packages/java/parser-jvm-plugin-model/src/main/java/dev/hilla/parser/plugins/model/ModelPlugin.java
  packages/java/parser-jvm-plugin-model/src/test/java/dev/hilla/parser/plugins/model/validation/ValidationEndpoint.java
  packages/java/parser-jvm-plugin-model/src/test/resources/dev/hilla/parser/plugins/model/validation/openapi.json
  packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/NonnullPlugin.java
  packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/basic/BasicEndpoint.java
  packages/java/parser-jvm-plugin-nonnull/src/test/resources/dev/hilla/parser/plugins/nonnull/basic/openapi.json
  packages/java/parser-jvm-plugin-transfertypes/src/main/java/dev/hilla/parser/plugins/transfertypes/TransferTypesPlugin.java
  packages/java/tests/spring/endpoints/frontend/src/test-type-script.ts
  packages/java/tests/spring/endpoints/src/main/java/com/vaadin/flow/connect/AnnotatedEndpoint.java
  packages/java/tests/spring/endpoints/src/test/java/com/vaadin/flow/connect/TypeScriptIT.java
Labels: hilla, target/2.0
