Repository vaadin/hilla, pull requests merged in 2023-06, with the labels that each got.

#1019 fix: enable overriding the plugins
  packages/java/engine-core/src/main/java/dev/hilla/engine/ParserConfiguration.java
  packages/java/engine-core/src/test/java/dev/hilla/engine/EngineConfigurationTest.java
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/core/PluginConfiguration.java
  packages/java/parser-jvm-plugin-nonnull/src/main/java/dev/hilla/parser/plugins/nonnull/AnnotationMatcher.java
  packages/java/parser-jvm-plugin-nonnull/src/test/java/dev/hilla/parser/plugins/nonnull/basic/BasicTest.java
Labels: target/2.0, target/2.1

#1003 Remove outdated link to docs
  README.md
Labels: target/1.3, target/2.0, target/2.1

#1036 [Snyk] Upgrade io.github.classgraph:classgraph from 4.8.158 to 4.8.160
  pom.xml
Labels: target/1.3, target/2.0, target/2.1

#1035 chore: improve app init feature
  packages/java/gradle-plugin/build.gradle
  packages/java/gradle-plugin/pom.xml
  packages/java/gradle-plugin/src/functionalTest/kotlin/dev/hilla/gradle/plugin/SingleModuleTest.kt
  packages/java/gradle-plugin/src/main/kotlin/dev/hilla/gradle/plugin/EngineInitAppTask.kt
  packages/java/maven-plugin/pom.xml
  packages/java/maven-plugin/src/main/java/dev/hilla/maven/InitAppMojo.java
  packages/java/plugin-base/pom.xml
  packages/java/plugin-base/src/main/java/dev/hilla/plugin/base/HillaAppInitUtility.java
  packages/java/plugin-base/src/test/java/dev/hilla/plugin/base/HillaAppInitUtilityTest.java
  pom.xml
Labels: target/2.1

#980 fix: see if sonarcloud stops complaining
  scripts/cherryPick.cjs
Labels: hilla

#1045 fix: create CommandRunner instance if build.gradle.kts was available
  packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/GradleRunner.java
  packages/java/engine-core/src/test/java/dev/hilla/engine/commandrunner/GradleRunnerTest.java
Labels: target/2.1

#1049 chore(gradle-plugin): fix URLs in Gradle Plugin metadata
  packages/java/gradle-plugin/build.gradle
Labels: target/2.1

#1053 chore: add README.md for Hilla Gradle Plugin
  packages/java/gradle-plugin/README.md
  packages/java/gradle-plugin/gradle-icon.svg
Labels: target/2.1

#1056 chore: update Node and npm requirements in README.md
  README.md
Labels: hilla, target/2.0, target/2.1

#1044 fix: use Java path of currently running java process to execute configure goal/task
  packages/java/engine-core/src/main/java/dev/hilla/engine/GeneratorShellRunner.java
  packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/CommandRunner.java
  packages/java/engine-core/src/test/java/dev/hilla/engine/commandrunner/CommandRunnerTest.java
Labels: target/2.0, target/2.1

#1059 fix: fix package extraction failure when package declaration is not first line
  packages/java/plugin-base/src/main/java/dev/hilla/plugin/base/HillaAppInitUtility.java
  packages/java/plugin-base/src/test/java/dev/hilla/plugin/base/HillaAppInitUtilityTest.java
Labels: target/2.1

#1065 [Snyk] Upgrade io.swagger.core.v3:swagger-models from 2.2.10 to 2.2.11
  pom.xml
Labels: target/1.3, target/2.0, target/2.1

#1076 build: add Windows run and skip-success workflows
  .github/workflows/skip-validation.yml
  .github/workflows/validation.yml
  packages/java/tests/pom.xml
  packages/java/tests/spring/pom.xml
Labels: target/2.0, target/2.1
