Repository vaadin/hilla, pull requests merged in 2023-07, with the labels that each got.

#1090 chore: fix regexp to allow dots in artifactId
  .github/workflows/validation.yml
Labels: target/2.1

#1088 chore: add portal pom to deploy gradle plugin in pre-releases repo
  packages/java/gradle-plugin/pom-portal.xml
  pom.xml
Labels: target/2.1

#1095 fix(jvm-parser): use gradle.exe as executable as well
  packages/java/engine-core/src/main/java/dev/hilla/engine/commandrunner/GradleRunner.java
Labels: hilla, target/2.1

#1121 [Snyk] Upgrade io.swagger.core.v3:swagger-core from 2.2.12 to 2.2.14
  pom.xml
Labels: target/2.0, target/2.1

#1115 fix: accept entities with no properties
  packages/ts/generator-typescript-plugin-backbone/src/EntityProcessor.ts
  packages/ts/generator-typescript-plugin-backbone/test/no-properties/NoProperties.json
  packages/ts/generator-typescript-plugin-backbone/test/no-properties/NoProperties.spec.ts
  packages/ts/generator-typescript-plugin-backbone/test/no-properties/fixtures/CoreEntity.snap.ts
  packages/ts/generator-typescript-plugin-backbone/test/no-properties/fixtures/ExampleEntity.snap.ts
  packages/ts/generator-typescript-plugin-backbone/test/no-properties/fixtures/NoPropertiesEndpoint.snap.ts
Labels: target/main, target/2.1
