Repository vaadin/hilla, pull requests merged in 2023-01, with the labels that each got.

#721 chore(release): make package-lock.json npm 8 compatible
  package-lock.json
Labels: hilla, react

#713 fix(generator-typescript-plugin-model): fix generating empty annotations
  package-lock.json
  package.json
  packages/ts/generator-typescript-plugin-model/src/Annotation.ts
  packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts
  packages/ts/generator-typescript-plugin-model/src/annotation.ts
  packages/ts/generator-typescript-plugin-model/src/parseAnnotation.ts
  packages/ts/generator-typescript-plugin-model/test/model/AnnotationParser.spec.ts
  packages/ts/generator-typescript-plugin-model/test/model/Model.spec.ts
  packages/ts/generator-typescript-plugin-model/test/model/parseAnnotation.spec.ts
  packages/ts/generator-typescript-utils/package.json
  packages/ts/generator-typescript-utils/src/ast.ts
Labels: hilla

#727 test(java/tests): add required webdrivermanager dependency
  packages/java/tests/pom.xml
Labels: hilla, target/1.2, target/1.3
