Repository vaadin/hilla, pull requests merged in 2023-08, with the labels that each got.

#1128 [Snyk] Upgrade io.swagger.core.v3:swagger-core from 2.2.14 to 2.2.15
  pom.xml
Labels: target/2.0, target/2.1

#1143 refactor(form): apply Vaadin ESLint rules
  packages/ts/form/.eslintrc
  packages/ts/form/.lintstagedrc.js
  packages/ts/form/package.json
  packages/ts/form/src/Binder.ts
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/src/Field.ts
  packages/ts/form/src/Models.ts
  packages/ts/form/src/Validation.ts
  packages/ts/form/src/Validators.ts
  packages/ts/form/src/Validity.ts
  packages/ts/form/src/index.ts
  packages/ts/form/src/types.d.ts
  packages/ts/form/test/Binder.test.ts
  packages/ts/form/test/Field.test.ts
  packages/ts/form/test/Index.test.ts
  packages/ts/form/test/Model.test.ts
  packages/ts/form/test/TestModels.ts
  packages/ts/form/test/Validation.test.ts
  packages/ts/form/test/Validators.test.ts
  packages/ts/form/tsconfig.build.json
Labels: hilla

#1151 chore: address SonarCloud DoS-related issues
  packages/ts/form/src/Validators.ts
  packages/ts/form/test/Validators.test.ts
Labels: hilla, target/1.3, target/2.0, target/2.1

#1152 fix: don't count minus sign in integer digits
  packages/ts/form/src/Validators.ts
  packages/ts/form/test/Validators.test.ts
Labels: target/1.3, target/2.0, target/2.1

#1155 fix(form): revert unintentional onSubmit API change
  packages/ts/form/src/BinderRoot.ts
  packages/ts/form/test/Validation.test.ts
Labels: hilla

#1157 feat: display React form value and validation state
  packages/ts/form/src/index.ts
  packages/ts/react-form/src/index.ts
Labels: hilla

#1162 fix(ts): make Binder work in non-browser environment
  packages/ts/form/src/BinderRoot.ts
  packages/ts/hilla-frontend/package.json
  packages/ts/hilla-frontend/src/Connect.ts
  packages/ts/hilla-frontend/src/EndpointErrors.ts
  packages/ts/hilla-frontend/src/index.ts
Labels: hilla

#1166 test(generator-typescript-cli): fix test failure on Windows & upgrade test implementation
  package-lock.json
  packages/ts/generator-typescript-cli/package.json
  packages/ts/generator-typescript-cli/test/GeneratorIO.spec.ts
Labels: hilla

#1171 fix(react-form): consistent render updates
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/test/useBinder.spec.tsx
Labels: hilla

#1178 fix(TypeScript): consistent validation updates in React forms
  packages/ts/form/src/BinderRoot.ts
  packages/ts/form/src/Field.ts
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/test/models.ts
  packages/ts/react-form/test/useBinder.spec.tsx
Labels: hilla

#1176 refactor(generator-typescript-cli): disable the test that fails on Windows & add small improvements
  packages/ts/generator-typescript-cli/src/GeneratorIO.ts
  packages/ts/generator-typescript-cli/test/GeneratorIO.spec.ts
Labels: hilla
