Repository vaadin/hilla, pull requests merged in 2023-04, with the labels that each got.

#870 chore(tests): validation with two IT test groups in parallel
  .github/workflows/validation.yml
  packages/java/tests/pom.xml
  packages/java/tests/spring/pom.xml
Labels: hilla, target/1.3, target/2.0

#860 chore: Sync Atmosphere version with Flow
  packages/java/endpoint/pom.xml
Labels: hilla, target/2.0

#892 chore: update TestBench to make tests pass again (2.0)
  packages/java/tests/csrf-context/package-lock.json
  packages/java/tests/csrf-context/package.json
  packages/java/tests/csrf/package-lock.json
  packages/java/tests/csrf/package.json
  packages/java/tests/spring/endpoints-custom-client/package-lock.json
  packages/java/tests/spring/endpoints-custom-client/package.json
  packages/java/tests/spring/endpoints-discovery/package-lock.json
  packages/java/tests/spring/endpoints-discovery/package.json
  packages/java/tests/spring/endpoints-latest-java/package-lock.json
  packages/java/tests/spring/endpoints-latest-java/package.json
  packages/java/tests/spring/endpoints-maven-engine/package-lock.json
  packages/java/tests/spring/endpoints-maven-engine/package.json
  packages/java/tests/spring/endpoints/package-lock.json
  packages/java/tests/spring/endpoints/package.json
  packages/java/tests/spring/security-contextpath/package-lock.json
  packages/java/tests/spring/security-contextpath/package.json
  packages/java/tests/spring/security-jwt/package-lock.json
  packages/java/tests/spring/security-jwt/package.json
  packages/java/tests/spring/security-urlmapping/package-lock.json
  packages/java/tests/spring/security-urlmapping/package.json
  packages/java/tests/spring/security/package-lock.json
  packages/java/tests/spring/security/package.json
  pom.xml
Labels: hilla

#893 test: fix compile errors in tests
  packages/java/engine-runtime/src/test/java/dev/hilla/internal/TaskTest.java
  packages/java/tests/csrf-context/package-lock.json
  packages/java/tests/csrf-context/package.json
  packages/java/tests/csrf/package-lock.json
  packages/java/tests/csrf/package.json
  packages/java/tests/pom.xml
  packages/java/tests/spring/endpoints-custom-client/frontend/index.ts
  packages/java/tests/spring/endpoints-custom-client/package-lock.json
  packages/java/tests/spring/endpoints-custom-client/package.json
  packages/java/tests/spring/endpoints-discovery/package-lock.json
  packages/java/tests/spring/endpoints-discovery/package.json
  packages/java/tests/spring/endpoints-latest-java/package-lock.json
  packages/java/tests/spring/endpoints-latest-java/package.json
  packages/java/tests/spring/endpoints-maven-engine/package-lock.json
  packages/java/tests/spring/endpoints-maven-engine/package.json
  packages/java/tests/spring/endpoints/package-lock.json
  packages/java/tests/spring/endpoints/package.json
  packages/java/tests/spring/security-contextpath/package-lock.json
  packages/java/tests/spring/security-contextpath/package.json
  packages/java/tests/spring/security-jwt/package-lock.json
  packages/java/tests/spring/security-jwt/package.json
  packages/java/tests/spring/security-urlmapping/package-lock.json
  packages/java/tests/spring/security-urlmapping/package.json
  packages/java/tests/spring/security/package-lock.json
  packages/java/tests/spring/security/package.json
  pom.xml
Labels: hilla

#894 chore: update TestBench to make tests pass again (1.3)
  packages/java/tests/csrf-context/package-lock.json
  packages/java/tests/csrf-context/package.json
  packages/java/tests/csrf/package-lock.json
  packages/java/tests/csrf/package.json
  packages/java/tests/spring/endpoints-custom-client/package-lock.json
  packages/java/tests/spring/endpoints-custom-client/package.json
  packages/java/tests/spring/endpoints-latest-java/package-lock.json
  packages/java/tests/spring/endpoints-latest-java/package.json
  packages/java/tests/spring/endpoints/package-lock.json
  packages/java/tests/spring/endpoints/package.json
  packages/java/tests/spring/pom.xml
  packages/java/tests/spring/security-contextpath/package-lock.json
  packages/java/tests/spring/security-contextpath/package.json
  packages/java/tests/spring/security-jwt/package-lock.json
  packages/java/tests/spring/security-jwt/package.json
  packages/java/tests/spring/security-urlmapping/package-lock.json
  packages/java/tests/spring/security-urlmapping/package.json
  packages/java/tests/spring/security/package-lock.json
  packages/java/tests/spring/security/package.json
  pom.xml
Labels: hilla

#895 fix: allow to create modules with spaces in names
  .github/workflows/validation.yml
  .lintstagedrc.cjs
Labels: hilla, target/2.0

#884 chore: rename a test using spaces
  packages/java/tests/spring/endpoints discovery/frontend/index.html
  packages/java/tests/spring/endpoints discovery/package-lock.json
  packages/java/tests/spring/endpoints discovery/package.json
  packages/java/tests/spring/endpoints discovery/pom.xml
  packages/java/tests/spring/endpoints discovery/src/main/java/com/example/application/Application.java
  packages/java/tests/spring/endpoints discovery/src/main/java/com/example/application/ExampleEndpoint.java
  packages/java/tests/spring/endpoints discovery/src/main/java/com/example/application/ExampleEntity.java
  packages/java/tests/spring/endpoints discovery/src/main/java/com/external/ExternalEndpoint.java
  packages/java/tests/spring/endpoints discovery/src/main/java/com/external/ExternalEntity.java
  packages/java/tests/spring/endpoints discovery/src/main/java/com/external2/ExternalEntity2.java
  packages/java/tests/spring/endpoints discovery/src/main/java/com/invalid/InvalidEndpoint.java
  packages/java/tests/spring/endpoints discovery/src/main/resources/application.properties
  packages/java/tests/spring/endpoints discovery/src/test/java/dev/hilla/endpoint/EndpointGenerationIT.java
  packages/java/tests/spring/pom.xml
Labels: hilla, target/2.0

#898 chore: enable dependencyConvergence and logging-imports enforcer
  packages/java/endpoint/pom.xml
  packages/java/engine-core/pom.xml
  packages/java/parser-jvm-utils/pom.xml
  packages/java/tests/csrf/pom.xml
  packages/java/tests/pom.xml
  packages/java/tests/spring/pom.xml
  packages/java/tests/spring/security/pom.xml
  pom.xml
Labels: hilla

#911 fix(form): error message not displayed in invalid fields
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/src/Field.ts
  packages/ts/form/test/Field.test.ts
  packages/ts/form/test/Validation.test.ts
Labels: hilla
