Repository vaadin/hilla, pull requests merged in 2023-09, with the labels that each got.

#1198 refactor(react-form): rename API entrypoints
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/test/useForm.spec.tsx
Labels: hilla

#1217 fix(parser-jvm-core): Filter synthetic methods
  packages/java/parser-jvm-core/src/main/java/dev/hilla/parser/models/ClassInfoReflectionModel.java
  packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/generics/ConcreteType.java
  packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/generics/GenericInterface.java
  packages/java/parser-jvm-plugin-backbone/src/test/java/dev/hilla/parser/plugins/backbone/generics/ImplementInterfaceEndpoint.java
  packages/java/parser-jvm-plugin-backbone/src/test/resources/dev/hilla/parser/plugins/backbone/generics/openapi.json
Labels: target/1.3, target/2.0, target/2.1

#1246 update flow to latest 24.1.11
  pom.xml
Labels: target/2.2

#1263 refactor(react-grid): small typing and style improvements
  packages/ts/react-grid/src/autogrid.tsx
  packages/ts/react-grid/src/utils.ts
Labels: hilla

#1289 fix(react-form): enable eslint checks
  packages/ts/react-form/package.json
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/src/types.d.ts
  packages/ts/react-form/test/models.ts
  packages/ts/react-form/test/useForm.spec.tsx
  packages/ts/react-grid/package.json
Labels: hilla

#1256 refactor(generator-typescript-plugin-model): update code according to #1252
  packages/ts/generator-typescript-plugin-model/src/EntityModelProcessor.ts
  packages/ts/generator-typescript-plugin-model/src/ModelSchemaProcessor.ts
  packages/ts/generator-typescript-plugin-model/src/utils.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormAnnotationsModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormArrayTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormDataPrimitivesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityHierarchyModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityIdModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEntityModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormEnumTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormNonnullTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormOptionalTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormRecordTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormTemporalTypesModel.snap.ts
  packages/ts/generator-typescript-plugin-model/test/model/fixtures/FormValidationConstraintsModel.snap.ts
Labels: hilla

#1257 refactor(react-form): update code according to #1252
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/src/types.d.ts
  packages/ts/react-form/test/models.ts
  packages/ts/react-form/test/useForm.spec.tsx
Labels: hilla
