Repository vaadin/hilla, pull requests merged in 2024-12, with the labels that each got.

#2934 fix(file-router): allow extension to apply on a route wrapper
  package-lock.json
  packages/ts/file-router/package.json
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/src/runtime/createRoute.ts
  packages/ts/file-router/src/shared/transformTree.ts
  packages/ts/file-router/src/vite-plugin/applyLayouts.ts
  packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts
  packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
  packages/ts/file-router/src/vite-plugin/generateRuntimeFiles.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
  packages/ts/file-router/test/vite-plugin/applyLayouts.spec.ts
  packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
Labels: hilla

#2968 chore: bump remaining 24.6 versions to 24.7
  packages/java/tests/csrf-context/package-lock.json
  packages/java/tests/csrf/package-lock.json
  packages/java/tests/gradle/single-module-tests/gradle.properties
  packages/java/tests/gradle/single-module-tests/package-lock.json
  packages/java/tests/gradle/single-module-tests/package.json
  packages/java/tests/gradle/single-module/gradle.properties
  packages/java/tests/gradle/single-module/package-lock.json
  packages/java/tests/gradle/single-module/package.json
  packages/java/tests/pom.xml
  packages/java/tests/spring/endpoints discovery/package-lock.json
  packages/java/tests/spring/endpoints-contextpath/package-lock.json
  packages/java/tests/spring/endpoints-custom-client/package-lock.json
  packages/java/tests/spring/endpoints-latest-java/package-lock.json
  packages/java/tests/spring/endpoints-maven-engine/package-lock.json
  packages/java/tests/spring/endpoints-maven-engine/package.json
  packages/java/tests/spring/endpoints-maven-engine/pom.xml
  packages/java/tests/spring/endpoints/package-lock.json
  packages/java/tests/spring/native/package-lock.json
  packages/java/tests/spring/native/package.json
  packages/java/tests/spring/react-grid-test/package-lock.json
  packages/java/tests/spring/react-i18n/package-lock.json
  packages/java/tests/spring/react-signals/package-lock.json
  packages/java/tests/spring/security-contextpath/package-lock.json
  packages/java/tests/spring/security-jwt/package-lock.json
  packages/java/tests/spring/security-urlmapping/package-lock.json
  packages/java/tests/spring/security/package-lock.json
Labels: hilla

#2963 chore: Bump dependencies
  package-lock.json
  package.json
  packages/ts/models/package.json
  packages/ts/react-auth/package.json
  packages/ts/react-crud/package.json
  packages/ts/react-form/package.json
  packages/ts/react-i18n/package.json
  packages/ts/react-signals/package.json
Labels: target/24.6

#2971 fix(file-router): allow routes with the same path
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
Labels: target/24.6

#2978 fix: Make file route HMR work on Windows
  packages/ts/file-router/src/vite-plugin.ts
Labels: target/24.4, target/24.5, target/24.6

#2989 fix(file-router): enable file routes + layout + fallback combination
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
Labels: hilla, target/24.6

#2958 fix!: mark ValidationResult constructors as private
  packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/operation/ValidationResult.java
Labels: hilla, target/24.6

#3001 chore: fix java doc
  packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvoker.java
Labels: hilla, target/24.6

#3010 test: Match nimbus-jose-jwt version with license-checker
  packages/java/tests/spring/pom.xml
Labels: target/24.5, target/24.6

#2999 fix: set NullHandling to native when sorting
  packages/ts/react-crud/src/data-provider.ts
  packages/ts/react-crud/test/autogrid.spec.tsx
  packages/ts/react-crud/test/dataprovider.spec.tsx
Labels: target/24.6

#3006 chore: Use Spring Boot 3.4
  packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/JsonValuePlugin.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/PropertyPlugin.java
  packages/java/parser-jvm-plugin-model/src/test/resources/com/vaadin/hilla/parser/plugins/model/validation/openapi.json
  pom.xml
Labels: target/24.6

#3028 test: Define window size
  karma.config.cjs
Labels: target/24.4, target/24.5, target/24.6

#3032 test: Fix viewport size for test for real
  karma.config.cjs
  packages/ts/react-crud/test/autoform.spec.tsx
Labels: target/24.4, target/24.5, target/24.6

#3023 chore: Bump preact
  package-lock.json
  package.json
  packages/ts/react-signals/package.json
Labels: target/24.6

#3024 chore: Bump Typescript in all packages
  package-lock.json
  packages/ts/file-router/package.json
  packages/ts/frontend/package.json
  packages/ts/generator-core/package.json
  packages/ts/generator-plugin-backbone/package.json
  packages/ts/generator-plugin-barrel/package.json
  packages/ts/generator-plugin-client/package.json
  packages/ts/generator-plugin-model/package.json
  packages/ts/generator-plugin-push/package.json
  packages/ts/generator-plugin-signals/package.json
  packages/ts/generator-plugin-subtypes/package.json
  packages/ts/generator-utils/package.json
  packages/ts/lit-form/package.json
  packages/ts/models/package.json
  packages/ts/react-auth/package.json
  packages/ts/react-crud/package.json
  packages/ts/react-form/package.json
  packages/ts/react-i18n/package.json
  packages/ts/react-signals/package.json
Labels: target/24.6

#3041 chore: Bump patch and minor versions
  package.json
  packages/ts/file-router/package.json
  packages/ts/frontend/package.json
  packages/ts/generator-cli/package.json
  packages/ts/generator-core/package.json
  packages/ts/generator-plugin-backbone/package.json
  packages/ts/generator-plugin-barrel/package.json
  packages/ts/generator-plugin-client/package.json
  packages/ts/generator-plugin-model/package.json
  packages/ts/generator-plugin-push/package.json
  packages/ts/generator-plugin-signals/package.json
  packages/ts/generator-plugin-subtypes/package.json
  packages/ts/generator-utils/package.json
  packages/ts/lit-form/package.json
  packages/ts/models/package.json
  packages/ts/react-auth/package.json
  packages/ts/react-crud/package.json
  packages/ts/react-form/package.json
  packages/ts/react-i18n/package.json
  packages/ts/react-signals/package.json
Labels: target/24.5, target/24.6

#3047 fix: Make JpaFilterConverter work without an EntityManager
  packages/java/endpoint/src/main/java/com/vaadin/hilla/crud/CrudConfiguration.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/crud/JpaFilterConverter.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/crud/ListRepositoryService.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/crud/PropertyStringFilterSpecification.java
  packages/java/endpoint/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/CrudRepositoryServiceTest.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/FilterTest.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/TestApplication.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/crud/filter/FilterTransformerTest.java
Labels: target/24.6

#3067 chore: update Spring Boot to 3.4.1
  pom.xml
Labels: target/24.6

#3072 chore: Change the code so Eclipse JDT accepts it is ok
  packages/java/parser-jvm-core/src/main/java/com/vaadin/hilla/parser/core/ScanResult.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/EndpointExposedPlugin.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/JsonValuePlugin.java
Labels: target/24.6

#2939 fix: log operation validator messages
  packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/Signal.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/core/event/StateEvent.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/signals/ValueSignalTest.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/signals/core/event/StateEventTest.java
  packages/ts/react-signals/src/ListSignal.ts
  packages/ts/react-signals/src/ValueSignal.ts
Labels: hilla, target/24.6

#2998 fix: throw exception if feature flag is not enabled
  packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/config/SignalsConfiguration.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/signals/handler/SignalsHandler.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/signals/handler/SignalsHandlerTest.java
  packages/ts/react-signals/src/FullStackSignal.ts
  packages/ts/react-signals/test/FeatureFlag.spec.ts
  packages/ts/react-signals/test/FullStackSignal.spec.tsx
  packages/ts/react-signals/test/NumberSignal.spec.tsx
  packages/ts/react-signals/test/ValueSignal.spec.tsx
  packages/ts/react-signals/test/events.spec.ts
  packages/ts/react-signals/test/setup.ts
Labels: hilla, target/24.6

#3090 chore: Bump react types
  packages/ts/models/package.json
  packages/ts/react-auth/package.json
  packages/ts/react-crud/package.json
  packages/ts/react-form/package.json
  packages/ts/react-i18n/package.json
  packages/ts/react-signals/package.json
Labels: target/24.6

#3088 chore: Make compatible with React 19 types
  packages/ts/react-crud/src/autogrid.tsx
  packages/ts/react-crud/src/header-filter.tsx
Labels: target/24.6

#3089 test: Use project .npmrc for tests
  packages/java/engine-runtime/src/test/java/com/vaadin/hilla/internal/TaskTest.java
Labels: target/24.6
