Repository vaadin/hilla, pull requests merged in 2024-11, with the labels that each got.

#2894 fix(crud): use 3-params overload for dates instead of separate assignments
  packages/ts/react-crud/src/locale.ts
Labels: target/24.4, target/24.5

#2904 chore(ts): update react-router-dom dependency version
  package-lock.json
  packages/ts/file-router/package.json
  packages/ts/react-auth/package.json
  packages/ts/react-signals/package.json
Labels: hilla, target/24.5

#2853 fix: handle child layouts
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
Labels: target/24.5

#2906 chore(ts): update react-router-dom dependency version (#2904) (CP: 24.5)
  package-lock.json
  packages/ts/file-router/package.json
  packages/ts/react-auth/package.json
  packages/ts/react-signals/package.json
Labels: hilla

#2911 test: refactor mock setup in maven plugin tests
  packages/java/maven-plugin/src/test/java/com/vaadin/hilla/maven/AbstractMojoTest.java
  packages/java/maven-plugin/src/test/java/com/vaadin/hilla/maven/EngineGenerateMojoTest.java
  packages/java/maven-plugin/src/test/resources/com/vaadin/hilla/maven/hilla-engine-configuration.json
Labels: target/24.4, target/24.5

#2915 feat(file-router): add skipLayouts feature
  package-lock.json
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/src/runtime/createRoute.ts
  packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
  packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
Labels: hilla
