Repository vaadin/hilla, pull requests merged in 2024-05, with the labels that each got.

#2364 feat(file-router): allow to set router options & make baseURI default
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/src/types.d.ts
  packages/ts/file-router/test/mocks/dom.ts
  packages/ts/file-router/test/runtime/RouterBuilder.spec.tsx
Labels: hilla

#2407 chore: fix ts build script
  scripts/prepare/index.ts
Labels: target/24.4

#2401 chore: change ClientViewMenuConfig order type
  packages/java/endpoint/src/main/java/com/vaadin/hilla/route/records/ClientViewMenuConfig.java
Labels: target/24.4

#2416 build: carry generated vaadin-core-versions.json between CI jobs
  .github/workflows/validation.yml
Labels: hilla, target/24.4

#2394 chore: add package.properties
  packages/java/endpoint/src/main/resources/META-INF/VAADIN/package.properties
Labels: target/24.4

#2411 fix(file-router): improve the speed of the HMR injection
  packages/ts/file-router/src/vite-plugin.ts
Labels: hilla, target/24.4

#2106 chore: remove Lumo / Material class copies
  .gitignore
  packages/java/tests/gradle/single-module-tests/build.gradle
  packages/java/tests/gradle/single-module-tests/gradle.properties
  packages/java/tests/gradle/single-module/build.gradle
  packages/java/tests/gradle/single-module/gradle.properties
  packages/java/tests/pom.xml
  packages/java/tests/spring/react-grid-test/pom.xml
  packages/java/tests/spring/react-signals/pom.xml
  scripts/prepare/config.ts
  scripts/prepare/index.ts
Labels: target/24.4

#2403 [Snyk] Upgrade io.github.classgraph:classgraph from 4.8.170 to 4.8.171
  pom.xml
Labels: target/24.4

#2423 fix: ignore absence of file-routes.json at startup in dev mode
  packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java
Labels: target/24.4

#2353 fix: adjust Hilla statistics collection
  packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointController.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvoker.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/HillaStats.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/HillaStatsTest.java
  packages/ts/file-router/src/runtime/createMenuItems.ts
  scripts/hooks.js
  scripts/hooks/stats.js
  scripts/register.js
Labels: target/24.4

#2443 refactor(file-router): forbid same names for sibling file and directory
  .gitignore
  package-lock.json
  packages/ts/file-router/package.json
  packages/ts/file-router/src/vite-plugin/collectRoutesFromFS.ts
  packages/ts/file-router/test/vite-plugin/collectRoutesFromFS.spec.ts
  packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
  packages/ts/file-router/test/vite-plugin/generateRuntimeFiles.spec.ts
  packages/ts/generator-cli/package.json
  packages/ts/generator-core/package.json
  packages/ts/generator-plugin-backbone/package.json
  packages/ts/generator-plugin-barrel/package.json
  packages/ts/generator-plugin-client/package.json
  packages/ts/generator-plugin-model/package.json
  packages/ts/generator-plugin-push/package.json
  packages/ts/generator-plugin-subtypes/package.json
  packages/ts/generator-utils/package.json
  packages/ts/react-signals/package.json
Labels: hilla, target/24.4

#2396 fix: add resource pattern for file-routes.json
  packages/java/endpoint/src/main/java/com/vaadin/hilla/springnative/HillaHintsRegistrar.java
Labels: target/24.4

#2392 refactor: disallow parametrized items in auto menu
  packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-admin.json
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-anonymous.json
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-user.json
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/only-client-views.json
  packages/ts/file-router/src/runtime/createMenuItems.ts
  packages/ts/file-router/src/shared/internal.d.ts
  packages/ts/file-router/test/runtime/createMenuItems.spec.ts
Labels: hilla, target/24.4

#2450 chore: upgrade TB to 9.3.0.beta2
  pom.xml
Labels: target/24.4

#2452 chore: remove redundant console log
  scripts/hooks/stats.js
Labels: target/24.4

#2448 refactor(file-router): tune server routes addition in case of variable routes presented
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/src/vite-plugin/collectRoutesFromFS.ts
  packages/ts/file-router/src/vite-plugin/utils.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
  packages/ts/file-router/test/vite-plugin/collectRoutesFromFS.spec.ts
Labels: hilla, target/24.4

#2457 refactor: adjust route analysis & transformation (#2443, #2448) (CP: 24.4)
  .gitignore
  package-lock.json
  packages/ts/file-router/package.json
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/src/vite-plugin/collectRoutesFromFS.ts
  packages/ts/file-router/src/vite-plugin/utils.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
  packages/ts/file-router/test/vite-plugin/collectRoutesFromFS.spec.ts
  packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
  packages/ts/file-router/test/vite-plugin/generateRuntimeFiles.spec.ts
  packages/ts/generator-cli/package.json
  packages/ts/generator-core/package.json
  packages/ts/generator-plugin-backbone/package.json
  packages/ts/generator-plugin-barrel/package.json
  packages/ts/generator-plugin-client/package.json
  packages/ts/generator-plugin-model/package.json
  packages/ts/generator-plugin-push/package.json
  packages/ts/generator-plugin-subtypes/package.json
  packages/ts/generator-utils/package.json
  packages/ts/react-signals/package.json
Labels: hilla

#2459 chore: upgrade TB to 9.3.0.rc1
  pom.xml
Labels: target/main

#2467 fix: Do not skip endpoint registration if there are no custom types
  packages/java/endpoint/src/main/java/com/vaadin/hilla/OpenAPIUtil.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/OpenAPIUtilTest.java
  packages/java/endpoint/src/test/resources/com/vaadin/hilla/openapi-noendpoints.json
Labels: target/main

#2472 test(endpoint): ignore route parameters
  packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-admin.json
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-anonymous.json
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/available-views-user.json
Labels: hilla

#2474 test: move some IT modules to windows
  .github/workflows/validation.yml
  packages/java/tests/pom.xml
  packages/java/tests/spring/pom.xml
Labels: hilla

#2432 feat!(frontend): reload the page on login / logout success
  packages/java/tests/spring/security-urlmapping/frontend/connect-client.ts
  packages/java/tests/spring/security/frontend/auth.ts
  packages/java/tests/spring/security/frontend/connect-client.ts
  packages/java/tests/spring/security/frontend/views/login-view.ts
  packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/SecurityConfig.java
  packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
  packages/ts/frontend/src/Authentication.ts
  packages/ts/frontend/test/Authentication.test.ts
  packages/ts/react-auth/src/useAuth.tsx
Labels: hilla, target/24.4

#2485 fix(engine-runtime): skip generating endpoints in prepare-frontend
  packages/java/engine-runtime/src/main/java/com/vaadin/hilla/internal/EndpointGeneratorTaskFactoryImpl.java
  packages/java/engine-runtime/src/test/java/com/vaadin/hilla/internal/NodeTasksEndpointTest.java
Labels: hilla

#2486 chore: update IT tests to use 24.5 components
  packages/java/tests/pom.xml
Labels: hilla

#2491 fix(file-router): support config below view
  packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts
  packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
  packages/ts/file-router/test/utils.tsx
  packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
  packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
Labels: hilla, target/main

#2493 refactor(file-router): make route with non-null children detected as a layout
  packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/file-routes.json
  packages/ts/file-router/src/shared/internal.d.ts
  packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
  packages/ts/file-router/test/utils.tsx
  packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
Labels: hilla, target/24.4
