Repository vaadin/hilla, pull requests merged in 2024-06, with the labels that each got.

#2498 refactor(file-router): make route with non-null children detected as a layout (#2493) (CP: 24.4)
  packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ClientRouteRegistry.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/file-routes.json
  packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
  packages/ts/file-router/test/utils.tsx
  packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
Labels: hilla

#2497 fix(binder): update form when array values change
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/test/models.ts
  packages/ts/react-form/test/useForm.spec.tsx
Labels: hilla, target/2.5, target/24.4

#2510 fix: replace validator/isNumeric with a simple NaN & Finite check
  packages/ts/lit-form/src/Validators.ts
  packages/ts/lit-form/test/Validators.test.ts
Labels: hilla, target/2.5, target/24.4

#2508 fix(form): initialize value / defaultValue keys when rendering optional fields
  packages/ts/form/src/BinderNode.ts
  packages/ts/form/test/Binder.test.ts
  packages/ts/form/test/TestModels.ts
  packages/ts/form/test/Validation.test.ts
Labels: hilla, target/main, target/24.4

#2515 fix(binder): update form when array values change (#2497) (CP: 2.5)
  packages/ts/react-form/src/index.ts
  packages/ts/react-form/test/models.ts
  packages/ts/react-form/test/useForm.spec.tsx
Labels: hilla

#2518 [Snyk] Upgrade io.swagger.core.v3:swagger-models from 2.2.21 to 2.2.22
  pom.xml
Labels: target/2.5, target/24.4

#2530 chore: upgrade to TB 9.3.0
  pom.xml
Labels: target/24.4

#2534 fix: Report usage stats when isReactEnabled=false
  packages/java/endpoint/src/main/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListener.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/startup/RouteUnifyingServiceInitListenerTest.java
Labels: target/24.4

#2556 chore: upgrade commons-io to 2.16.1
  pom.xml
Labels: target/24.4

#2567 chore:add repo declaration
  packages/java/hilla-bom/pom.xml
Labels: target/24.4

#2572 fix(file-router): preserve empty children for layout routes
  packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts
  packages/ts/file-router/test/utils.tsx
  packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
  packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
Labels: hilla, target/main

#2566 test: fix CI failures
  packages/ts/lit-form/package.json
  packages/ts/lit-form/test/Index.test.ts
  packages/ts/react-crud/test/autogrid.spec.tsx
Labels: hilla, target/2.5, target/24.4

#2557 fix: nested cases of route parameters in the menu (#2527) (CP: main)
  packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/server-and-client-views.json
  packages/java/endpoint/src/test/resources/com/vaadin/hilla/route/clientRoutes.json
  packages/java/endpoint/src/test/resources/com/vaadin/hilla/route/clientRoutesWithLayout.json
  packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
  packages/ts/file-router/test/utils.tsx
  packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
  packages/ts/file-router/test/vite-plugin/createViewConfigJson.spec.ts
Labels: hilla

#2560 chore: update c8 package and use monocart to collect the coverage correctly
  package-lock.json
  packages/ts/file-router/package.json
  packages/ts/generator-cli/package.json
  packages/ts/generator-core/package.json
  packages/ts/generator-plugin-backbone/package.json
  packages/ts/generator-plugin-barrel/package.json
  packages/ts/generator-plugin-client/package.json
  packages/ts/generator-plugin-model/package.json
  packages/ts/generator-plugin-push/package.json
  packages/ts/generator-plugin-subtypes/package.json
  packages/ts/generator-utils/package.json
  packages/ts/lit-form/test/Index.test.ts
Labels: hilla
