Repository vaadin/hilla, pull requests merged in 2024-10, with the labels that each got.

#2802 fix(IT): update router typings
  packages/java/tests/spring/security/frontend/routes.ts
  packages/java/tests/spring/security/frontend/views/login-view.ts
Labels: hilla

#2817 chore: remove redundant package names
  packages/java/hilla-dev/package-lock.json
  packages/java/hilla-dev/package.json
  packages/java/hilla-dev/pom.xml
  packages/java/hilla-dev/tsconfig.json
  packages/java/tests/csrf-context/package.json
  packages/java/tests/csrf/package.json
  packages/java/tests/gradle/single-module-tests/package.json
  packages/java/tests/gradle/single-module/package.json
  packages/java/tests/spring/endpoints discovery/package.json
  packages/java/tests/spring/endpoints-contextpath/package.json
  packages/java/tests/spring/endpoints-custom-client/package.json
  packages/java/tests/spring/endpoints-latest-java/package.json
  packages/java/tests/spring/endpoints-maven-engine/package.json
  packages/java/tests/spring/endpoints/package.json
  packages/java/tests/spring/native/package.json
  packages/java/tests/spring/react-grid-test/package.json
  packages/java/tests/spring/react-i18n/package.json
  packages/java/tests/spring/react-signals/package.json
  packages/java/tests/spring/security-contextpath/package.json
  packages/java/tests/spring/security-jwt/package.json
  packages/java/tests/spring/security-urlmapping/package.json
  packages/java/tests/spring/security/package.json
  scripts/prepare/templates/components/lit/package.json
  scripts/prepare/templates/components/react/package.json
Labels: target/main, target/2.5, target/1.5, target/24.4

#2796 fix: regenerate file-router files when layouts changes
  packages/ts/file-router/src/vite-plugin.ts
  packages/ts/file-router/test/vite-plugin/vite-plugin.spec.ts
Labels: target/24.5

#2831 fix: Check main layout presence separately
  packages/java/endpoint/src/main/java/com/vaadin/hilla/route/ServerAndClientViewsProvider.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
  packages/java/endpoint/src/test/resources/META-INF/VAADIN/server-and-client-views-layout-and-index-route.json
  packages/java/endpoint/src/test/resources/com/vaadin/hilla/route/clientRoutesWithLayoutAndIndexView.json
Labels: target/main

#2816 fix: invalidate binder node if bad input found by component already
  packages/ts/lit-form/src/Validation.ts
  packages/ts/lit-form/test/Validation.test.ts
Labels: target/24.4, target/24.5

#2848 fix(parser): add position information to type signature node
  packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/TypeSignaturePlugin.java
  packages/java/parser-jvm-plugin-backbone/src/main/java/com/vaadin/hilla/parser/plugins/backbone/nodes/TypeSignatureNode.java
  packages/java/parser-jvm-plugin-backbone/src/test/java/com/vaadin/hilla/parser/plugins/backbone/generics/GenericsBareEntityEndpoint.java
  packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/hilla/parser/plugins/backbone/generics/openapi.json
Labels: target/24.5

#2815 fix: ignore vaadin field old invalid state
  packages/ts/lit-form/src/Field.ts
  packages/ts/lit-form/test/Field.test.ts
Labels: target/24.4, target/24.5

#2863 test: fix MenuAccessControl mocking
  packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListenerTest.java
Labels: target/24.5

#2882 fix(form): support non-UTC timezone date time in VaadinDateTimePicker
  packages/ts/lit-form/package.json
  packages/ts/lit-form/src/Field.ts
Labels: target/main
