Repository vaadin/hilla, pull requests merged in 2025-06, with the labels that each got.

#3559 fix: implement `translateDynamic`
  packages/java/tests/spring/react-i18n/src/main/frontend/types/detail.ts
  packages/java/tests/spring/react-i18n/src/main/frontend/views/@index.tsx
  packages/java/tests/spring/react-i18n/src/main/frontend/views/@layout.tsx
  packages/java/tests/spring/react-i18n/src/main/frontend/views/basic-i18n.tsx
  packages/java/tests/spring/react-i18n/src/main/frontend/views/detail.ts
  packages/java/tests/spring/react-i18n/src/main/frontend/views/lazy.tsx
  packages/java/tests/spring/react-i18n/src/test/java/com/vaadin/hilla/test/ChunksTest.java
  packages/ts/file-router/src/vite-plugin/createViewConfigJson.ts
  packages/ts/react-i18n/src/backend.ts
  packages/ts/react-i18n/src/index.ts
  packages/ts/react-i18n/test/i18n.spec.tsx
Labels: target/24.8

#3576 fix(router): always add children, even if empty
  packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts
  packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
  packages/ts/file-router/test/vite-plugin/fixtures/createRoutesFromMeta/basic.snap.ts
  packages/ts/file-router/test/vite-plugin/fixtures/createRoutesFromMeta/duplicated-paths.snap.ts
Labels: target/24.8

#3591 fix(react-i18n): align with Flow i18n backend behavior
  packages/java/tests/spring/react-i18n/src/main/frontend/views/@layout.tsx
  packages/java/tests/spring/react-i18n/src/main/resources/vaadin-i18n/translations_es_AR.properties
  packages/java/tests/spring/react-i18n/src/test/java/com/vaadin/hilla/test/BasicI18NIT.java
  packages/ts/react-i18n/src/index.ts
  packages/ts/react-i18n/test/i18n.spec.tsx
Labels: target/24.8

#3597 chore: drop android-json dependency
  packages/java/endpoint/pom.xml
Labels: target/24.7, target/24.8

#3615 fix: Use Jakarta Swagger dependencies
  packages/java/parser-jvm-utils/pom.xml
Labels: target/main

#3624 chore: update javaparser and npm dependencies
  package-lock.json
  package.json
  packages/java/endpoint/src/main/java/com/vaadin/hilla/ApplicationContextProvider.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/ExplicitNullableTypeCheckerTest.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/route/RouteUtilTest.java
  packages/java/engine-runtime/pom.xml
  packages/java/engine-runtime/src/test/java/com/vaadin/hilla/internal/NoEndpointsTaskTest.java
  packages/java/tests/csrf-context/package.json
  packages/java/tests/csrf/package.json
  packages/java/tests/gradle/kotlin-gradle-test/package.json
  packages/java/tests/spring/endpoints discovery/package.json
  packages/java/tests/spring/endpoints-contextpath/package.json
  packages/java/tests/spring/endpoints-custom-client/package.json
  packages/java/tests/spring/endpoints-latest-java/package.json
  packages/java/tests/spring/endpoints/package.json
  packages/java/tests/spring/react-grid-test/package.json
  packages/java/tests/spring/react-i18n/package.json
  packages/java/tests/spring/react-signals/package.json
  packages/java/tests/spring/security-contextpath/package.json
  packages/java/tests/spring/security-jwt/package.json
  packages/java/tests/spring/security-urlmapping/package.json
  packages/java/tests/spring/security/package.json
  packages/ts/react-crud/package.json
  pom.xml
Labels: hilla

#3618 chore: upgrade testbench to 9.4.0
  pom.xml
Labels: target/24.8, cherry-picked-24.8

#3613 [Snyk] Upgrade io.swagger.core.v3:swagger-core from 2.2.30 to 2.2.32
  pom.xml
Labels: target/24.8
