Repository vaadin/hilla, pull requests merged in 2025-01, with the labels that each got.

#2959 fix(form): initialize arrays when receiving items
  packages/ts/lit-form/src/BinderNode.ts
  packages/ts/lit-form/test/Binder.test.ts
Labels: hilla, target/main, target/24.6

#3076 fix: clarify TS Docs for better DX
  packages/ts/react-signals/src/FullStackSignal.ts
  packages/ts/react-signals/src/ListSignal.ts
  packages/ts/react-signals/src/ValueSignal.ts
  packages/ts/react-signals/src/index.ts
Labels: target/24.6

#2902 feat(form): support validation change events
  packages/ts/lit-form/src/BinderNode.ts
  packages/ts/lit-form/src/BinderRoot.ts
  packages/ts/lit-form/src/Field.ts
  packages/ts/lit-form/test/Field.test.ts
  packages/ts/lit-form/test/Validation.test.ts
  packages/ts/react-form/src/index.ts
Labels: hilla

#3157 fix(binder): convert property paths in arrays to dot notation
  packages/ts/lit-form/src/BinderRoot.ts
  packages/ts/lit-form/test/Validation.test.ts
Labels: target/24.6
