Repository vaadin/hilla, pull requests merged in 2025-05, with the labels that each got.

#3458 chore: upgrade vaadin-parent to 2.2.2
  pom.xml
Labels: target/24.7

#3445 fix: submit form request to support OIDC logout
  packages/ts/frontend/src/Authentication.ts
  packages/ts/frontend/src/CsrfUtils.ts
  packages/ts/frontend/test/Authentication.test.ts
  packages/ts/frontend/test/SpringCsrfTestUtils.ts
Labels: target/24.7

#3480 chore: fix Vitest not stopping on breakpoints
  .run/Vitest Debug.run.xml
  packages/ts/file-router/package.json
  packages/ts/frontend/package.json
  packages/ts/generator-cli/package.json
  packages/ts/generator-core/package.json
  packages/ts/generator-plugin-backbone/package.json
  packages/ts/generator-plugin-barrel/package.json
  packages/ts/generator-plugin-client/package.json
  packages/ts/generator-plugin-model/package.json
  packages/ts/generator-plugin-push/package.json
  packages/ts/generator-plugin-signals/package.json
  packages/ts/generator-plugin-subtypes/package.json
  packages/ts/generator-plugin-transfertypes/package.json
  packages/ts/generator-utils/package.json
  packages/ts/lit-form/package.json
  packages/ts/models/package.json
  packages/ts/react-auth/package.json
  packages/ts/react-crud/package.json
  packages/ts/react-form/package.json
  packages/ts/react-i18n/package.json
  packages/ts/react-signals/package.json
  scripts/vite/browser.vitest.config.ts
Labels: hilla

#3491 chore: upgrade vaadin-parent to 3.0.0
  pom.xml
Labels: target/24.6, target/24.7

#3490 fix(frontend): make doFormLayout async and waiting
  packages/ts/frontend/src/Authentication.ts
  packages/ts/frontend/test/Authentication.test.ts
Labels: target/24.7

#3497 chore: dedup in package-lock.json (24.7)
  package-lock.json
  package.json
Labels: hilla

#3483 chore: upgrade to TB 9.3.12 (24.7)
  pom.xml
Labels: target/24.6

#3514 chore: upgrade springboot to 3.4.6 and Jackson to 2.18.4 (24.7)
  pom.xml
Labels: target/24.6

#3485 feat(engine): hide HTTP codes in exception classes
  packages/java/endpoint/src/main/java/com/vaadin/hilla/EndpointInvocationException.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/EndpointControllerTest.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/EndpointInvokerTest.java
Labels: target/24.8

#3531 chore: upgrade testbench to 9.4.0.beta1
  pom.xml
Labels: target/24.8

#3530 chore(i18n): remove feature flag references
  packages/java/endpoint/src/main/java/com/vaadin/hilla/push/PushConfigurer.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/push/PushMessageHandler.java
  packages/java/tests/spring/react-grid-test/src/main/resources/vaadin-featureflags.properties
  packages/java/tests/spring/react-i18n/src/main/resources/vaadin-featureflags.properties
  packages/ts/react-i18n/src/index.ts
  packages/ts/react-i18n/test/enable-feature-flag.ts
  packages/ts/react-i18n/test/i18n.spec.tsx
Labels: target/24.8

#3506 feat: synchronise csrf info with service worker
  packages/java/tests/spring/endpoints/frontend/src/test-component.js
  packages/java/tests/spring/endpoints/frontend/sw-app.ts
  packages/java/tests/spring/endpoints/src/test/java/com/vaadin/flow/connect/ServiceWorkerIT.java
  packages/ts/frontend/src/Authentication.ts
  packages/ts/frontend/src/Connect.ts
  packages/ts/frontend/src/CookieManager.ts
  packages/ts/frontend/src/CsrfInfoSource.ts
  packages/ts/frontend/src/CsrfUtils.ts
  packages/ts/frontend/src/FluxConnection.ts
  packages/ts/frontend/test/Authentication.test.ts
  packages/ts/frontend/test/Connect.test.ts
  packages/ts/frontend/test/FluxConnection.test.ts
Labels: hilla, target/24.8
