Repository vaadin/hilla, pull requests merged in 2025-02, with the labels that each got.

#3204 test: add fallback for Playwright-provided browser
  .github/workflows/validation.yml
  package-lock.json
  scripts/vite/browser.vitest.config.ts
Labels: hilla

#3215 fix(engine-core): use generator-plugin-transfertypes package
  packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/GeneratorConfiguration.java
  packages/ts/generator-core/src/PluginManager.ts
Labels: hilla

#3231 chore: update README.md
  README.md
Labels: target/24.4, target/24.5, target/24.6

#3235 fix(controller): do not propagate NonNullApi to other packages
  packages/java/endpoint/src/main/java/com/vaadin/hilla/ExplicitNullableTypeChecker.java
  packages/java/endpoint/src/main/java/com/vaadin/hilla/ExplicitNullableTypeCheckerHelper.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/EndpointControllerTest.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/ExplicitNullableTypeCheckerTest.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/nonnullapi/NonNullableEntity.java
  packages/java/endpoint/src/test/java/com/vaadin/hilla/nonnullapi/package-info.java
Labels: target/24.5, target/24.6

#3259 fix(file-router): correctly exclude children paths of "excluded" & paths with variable segments
  .eslintrc.json
  package-lock.json
  package.json
  packages/java/endpoint/src/main/java/com/vaadin/hilla/route/RouteUnifyingIndexHtmlRequestListener.java
  packages/ts/file-router/src/runtime/createMenuItems.ts
  packages/ts/file-router/test/runtime/createMenuItems.spec.ts
  packages/ts/file-router/test/utils.tsx
  scripts/vite/browser.vitest.config.ts
Labels: hilla

#3280 fix(file-router): enable server fallback with client layout and empty client routes
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
Labels: target/24.6

#3301 chore: use node-glob instead of native glob to support Node v20
  package-lock.json
  package.json
  scripts/build.ts
  scripts/fast-build.ts
  scripts/types.ts
Labels: target/24.7

#3214 refactor: use OpenAPI file path for generator instead of stdin & modernize generator-cli
  package-lock.json
  package.json
  packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/GeneratorProcessor.java
  packages/ts/generator-cli/package.json
  packages/ts/generator-cli/src/GeneratorIO.ts
  packages/ts/generator-cli/src/index.ts
  packages/ts/generator-cli/src/utils.ts
  packages/ts/generator-cli/test/GeneratorIO.spec.ts
  packages/ts/generator-cli/test/TestPlugin.ts
  packages/ts/generator-cli/test/cli.spec.ts
  packages/ts/generator-cli/test/fixtures/help.snap
Labels: hilla
