Repository vaadin/hilla, pull requests merged in 2025-04, with the labels that each got.

#3391 fix: register Hilla tasks upon applying SpringBoot plugin
  packages/java/gradle-plugin/src/main/kotlin/com/vaadin/hilla/gradle/plugin/HillaPlugin.kt
Labels: target/24.5, target/24.6, target/24.7

#3419 chore: TestBench 9.3.11
  pom.xml
Labels: target/24.6

#3447 feat!(engine): change default behavior for finding endpoints
  packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/EngineConfiguration.java
  packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/LookupBrowserCallableFinder.java
  packages/java/engine-core/src/test/java/com/vaadin/hilla/engine/EngineConfigurationTest.java
  packages/java/tests/spring/endpoints discovery/src/test/java/com/vaadin/hilla/endpoint/EndpointGenerationIT.java
Labels: hilla
