Repository vaadin/hilla, pull requests merged in 2025-08, with the labels that each got.

#3821 chore: bump spring-boot to 3.5.4
  packages/java/parser-jvm-plugin-backbone/src/test/resources/com/vaadin/hilla/parser/plugins/backbone/generics/openapi.json
  pom.xml
Labels: target/24.8

#3807 test(security): verify setup with sessions disabled and stateless security
  packages/java/tests/spring/security/frontend/views/private/private-view.ts
  packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/LegacySecurityConfig.java
  packages/java/tests/spring/security/src/main/java/com/vaadin/flow/spring/fusionsecurity/SecurityConfig.java
  packages/java/tests/spring/security/src/test/java/com/vaadin/flow/spring/fusionsecurity/SecurityIT.java
Labels: target/24.8, target/24.9

#3844 chore: upgrade testbench to 9.4.3
  pom.xml
Labels: target/24.8

#3836 refactor: make RouteConfigurationBuilder logic more detailed and self-documented
  packages/ts/file-router/src/runtime.ts
  packages/ts/file-router/src/runtime/RouterConfigurationBuilder.ts
  packages/ts/file-router/src/runtime/configuration-builder/RouterConfigurationBuilder.ts
  packages/ts/file-router/src/runtime/configuration-builder/createFallbackTransformer.ts
  packages/ts/file-router/src/runtime/configuration-builder/createProtectTransformer.ts
  packages/ts/file-router/src/runtime/configuration-builder/fileRouteTransformer.ts
  packages/ts/file-router/src/runtime/configuration-builder/mergeLayout.ts
  packages/ts/file-router/src/runtime/configuration-builder/mergeRouteTrees.ts
  packages/ts/file-router/src/runtime/configuration-builder/mergeSkipLayout.ts
  packages/ts/file-router/src/runtime/configuration-builder/utils.ts
  packages/ts/file-router/src/shared/transformTree.ts
  packages/ts/file-router/src/vite-plugin/collectRoutesFromFS.ts
  packages/ts/file-router/src/vite-plugin/createRoutesFromMeta.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
  packages/ts/file-router/test/vite-plugin/createRoutesFromMeta.spec.ts
  packages/ts/file-router/tsconfig.json
Labels: hilla

#3883 fix(file-router): restore original fallback logic
  packages/ts/file-router/src/runtime/configuration-builder/createFallbackTransformer.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
Labels: hilla, target/24.8, target/24.9

#3864 feat(file-router): propagate wildcard deeply to routes children
  package-lock.json
  packages/java/tests/spring/security-contextpath/package.json
  packages/java/tests/spring/security-jwt/package.json
  packages/java/tests/spring/security-urlmapping/package.json
  packages/ts/file-router/src/runtime/configuration-builder/RouterConfigurationBuilder.ts
  packages/ts/file-router/src/runtime/configuration-builder/createFallbackTransformer.ts
  packages/ts/file-router/src/runtime/configuration-builder/mergeDeepWildcard.ts
  packages/ts/file-router/src/runtime/configuration-builder/utils.ts
  packages/ts/file-router/test/runtime/RouterConfigurationBuilder.spec.tsx
  scripts/java/hilla-scripts/src/main/java/com/vaadin/hilla/scripts/FlowPackageJsonUpdater.java
Labels: hilla, target/24.9
